import type { Doctor } from "@/app/home/components/DoctorCard";

export const doctors: Doctor[] = [
  {
    name: "محمدرضا حیدری",
    score: 4,
    spec: "تخصص ندارد",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "علی رضایی",
    score: 5,
    spec: "متخصص قلب",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "مریم احمدی",
    score: 3,
    spec: "متخصص پوست",
    time: 10,
    image: "/doctor.jpg",
  },
  {
    name: "حسین موسوی",
    score: 4,
    spec: "متخصص مغز و اعصاب",
    time: 25,
    image: "/doctor.jpg",
  },
  {
    name: "زهرا کریمی",
    score: 5,
    spec: "متخصص اطفال",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "رضا حسینی",
    score: 4,
    spec: "متخصص ارتوپدی",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "سارا محمدی",
    score: 5,
    spec: "متخصص زنان",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "امیر عباسی",
    score: 3,
    spec: "متخصص چشم",
    time: 10,
    image: "/doctor.jpg",
  },
  {
    name: "لیلا صادقی",
    score: 4,
    spec: "متخصص گوش و حلق و بینی",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "محمد کریمی",
    score: 5,
    spec: "متخصص قلب",
    time: 30,
    image: "/doctor.jpg",
  },
  {
    name: "فاطمه نادری",
    score: 4,
    spec: "متخصص داخلی",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "حمید کاظمی",
    score: 3,
    spec: "متخصص پوست",
    time: 10,
    image: "/doctor.jpg",
  },
  {
    name: "ندا مرادی",
    score: 5,
    spec: "متخصص اطفال",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "احمد رستمی",
    score: 4,
    spec: "متخصص مغز و اعصاب",
    time: 25,
    image: "/doctor.jpg",
  },
  {
    name: "نگار تقوی",
    score: 5,
    spec: "متخصص چشم",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "کامران اسدی",
    score: 4,
    spec: "متخصص ارتوپدی",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "الهام یوسفی",
    score: 3,
    spec: "متخصص داخلی",
    time: 10,
    image: "/doctor.jpg",
  },
  {
    name: "مهدی جلالی",
    score: 4,
    spec: "متخصص قلب",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "پرستو صالحی",
    score: 5,
    spec: "متخصص زنان",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "بابک قاسمی",
    score: 4,
    spec: "متخصص گوش و حلق و بینی",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "مهسا شریفی",
    score: 5,
    spec: "متخصص پوست",
    time: 15,
    image: "/doctor.jpg",
  },
  {
    name: "یاسر زمانی",
    score: 3,
    spec: "متخصص داخلی",
    time: 10,
    image: "/doctor.jpg",
  },
  {
    name: "آرزو رحیمی",
    score: 4,
    spec: "متخصص اطفال",
    time: 20,
    image: "/doctor.jpg",
  },
  {
    name: "کیوان سلطانی",
    score: 5,
    spec: "متخصص مغز و اعصاب",
    time: 25,
    image: "/doctor.jpg",
  },
  {
    name: "سمیه خالقی",
    score: 4,
    spec: "متخصص چشم",
    time: 15,
    image: "/doctor.jpg",
  },
];
